### ISSUE TITLE
Crash when attempting to load a Zombie into the world (missing getUUID function in class Entity)

### ISSUE THREAD

**Issue by Jukabofy** [Xaidee/Zombie-Friends#1]
[crash-2022-10-31_11.09.40-client.txt](https://github.com/Xaidee/Zombie-Friends/files/9902807/crash-2022-10-31_11.09.40-client.txt)
I created a new world and after 2 ~ 3 seconds it crashed
Looks like is something with this mod

**Comment by Xaidee** [comment]
Thanks for the report, I thought I fixed this crash before releasing it but I guess not. I'll look into it ASAP.

**Comment by Freshah** [comment]
Also getting this crash about 20 seconds into loading new world

**Comment by Xaidee** [comment]
> Also getting this crash about 20 seconds into loading new world

Could you provide your modlist so i can compare it with Jukabofy's, I am struggling to recreate this issue when only Zombie Friends is installed

**Comment by Xaidee** [comment]
or just a crash report

**Comment by Xaidee** [comment]
[Zombie Friends 1.18-1.19-1.0.1.zip](https://github.com/Xaidee/Zombie-Friends/files/9925391/Zombie.Friends.1.18-1.19-1.0.1.zip)
Could you see if this build fixes it? 
GitHub doesn't allow me to upload jar files in comments so i sent it as a zip, you just need to rename the file extension from .zip to .jar, do not attempt to unzip.

**Comment by Freshah** [comment]
I'll give it a spin and send modlist after

**Comment by Freshah** [comment]
works!

**Comment by Xaidee** [comment]
Great to hear! I'll push out the patch on Curse Forge ^-^

**Comment by Jukabofy** [comment]
![2022-11-02_22 13 20](https://user-images.githubusercontent.com/87483832/199641383-d84499f0-b134-4524-a025-316bb868bf6f.png)
![2022-11-02_22 15 17](https://user-images.githubusercontent.com/87483832/199641386-175d7493-0ca3-419d-bec9-e078e8688125.png)
can confirm too
Thanks

**Comment by Jukabofy** [comment]
so, 1.0.2 is having the the same issue as 1.0.0 i'll downgrade to 1.0.1 again to see if it works again lol

**Comment by Jukabofy** [comment]
Yea, is working with 1.0.1 but not with 1.0.2 👀

**Comment by Xaidee** [comment]
I don't understand this bug 😭

**Comment by Jukabofy** [comment]
remember it crashes 1.0.0 and 1.0.2 for me but it works fine with 1.0.1 @Xaidee

**Comment by Coraline774477** [comment]
Can confirm since I've recently crashed upon spawning in my newly created world right after world creation with Zombie Friends 1.0.2.
(Caused by: java.lang.NoSuchMethodError: 'java.util.UUID net.minecraft.world.entity.Entity.m_142081_()')

Thanks to NotEnoughCrashes telling me that Zombie Friends and Xaero's Minimap caused my crash, what caused it was Xaero's Minimap tried to add your entities to it's radar system as icons for the minimap so that it can show their icon in the minimap and failed to do so cause of your UUID's since Xearo's minimap needs the UUID's of any entity to render in the mod's radar system in the minimap (and worldmap in Xaero's Worldmap) which I think it won't matter if I were to change the one setting in Xaero's Minimap to use dots as icons instead of mob heads as the icons that the game would still crash btw.

So Zombie Friends had started a fatal chain reaction upon world creation due to it's UUID's possibly being completely missing/broken which caused Xaero's Minimap to fail which then caused the game to fatally crash pretty hard.
You really need to find a permanent solution/fix for your UUID's Xaidee..

I'm just suggesting but maybe ask someone with a bit more knowledge with UUID's to help you with your UUID dilemma since you've tried multiple times to resolve the bug and it keeps coming back and you're not understanding what's truly going on behind the scenes completely to resolve the issue.

*_I'll go get Z.F 1.0.1 to see if 1.0.1 will work for me_ * with the other zombie type mods that I have since my new 1.19.2 world is a zombie apocalypse type world with Mr.Crayfish's Gun Mod and it's addon mods Additional Guns and it's sister Project Arinsal.
This mod would fit perfectly since I need/want more variations of zombies than just the regulars (Zombie, Zombie Villager, Husk and Drowned).

One last thing, here's my crash report and latest log: 

Crash Report: https://gist.github.com/Coraline774477/ee664e08ed79834103b74399a718404b
Latest Log: https://gist.github.com/Coraline774477/fe13c229063dfec8e6ac5bd7cee18bd6

*Unsecond thought maybe I shouldn't cause I rather be safe than sorry to avoid any more crashes from Z.F that may cause other issues like it did with Xaero's Minimap for instance even tho this mod would nicely fit with the theme of my zombie apocalypse world...
